spring:
  liquibase:
    change-log: "classpath:db/changelog.xml"
  application:
    name: "library"
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/library_db"
    username: "user"
    password: "user"
server:
  port: 8080
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"